### ISSUE TITLE
Only_attributes doesn't work when binary=FALSE

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#161]
```
> iquery(DB, "op_count(list())", return=T,  binary=FALSE)
  i count
1 0     7
> iquery(DB, "op_count(list())", return=T, only_attributes=T,  binary=FALSE)
Error in value[[3L]](cond) : SciDB query error
```

**Comment by bwlewis** [comment]
good catch. a dumb bug!

**Comment by bwlewis** [comment]
Or maybe I can put a default colClasses argument using the default type mapping list...

**Comment by apoliakov** [comment]
But shouldn't we be getting only one attribute? Why am I still getting the i?
```R
> iquery(DB, "op_count(list())", return=T,  binary=FALSE, only_attributes=T)
  i count
1 0     7
```

**Comment by bwlewis** [comment]
only_attributes is not documented for use with `iquery()` -- indeed the save path for binary=FALSE goes through the SciDB save operator (or whatever shim decides to replace it with) and csv+:1 format whatever that means.

So, nothing unexpected here or even expected since it's not documented. This is a feature request I think.

Do you want iquery to be able to save text data without dimensions? Can SciDB emit data in that form?

**Comment by apoliakov** [comment]
Yes SciDB can emit that data if you use plain `csv` for the format. I don't think I care that much for it - merely a nice-to-have. Didn't know only_attributes wasn't documented - it is definitely useful.

**Comment by bwlewis** [comment]
it's documented in as.R with some warnings. not ever documented for iquery.

how important is the non-binary only_attributes?

**Comment by apoliakov** [comment]
I don't think it's too important. I think this is fine.
