### ISSUE TITLE
Undesired type conversion when binary=FALSE

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#162]
I have some strings in the database like "01", "02", "03". When I bring them back with `binary=FALSE` they magically become integers for some reason:
```R
> t1=proc.time(); iquery(DB, "build(<val:string>[i=1:3], '[(01),(02),(03)]', true)", return=T); proc.time()-t1
  i val
1 1  01
2 2  02
3 3  03
   user  system elapsed 
  0.555   0.051   0.605 
> t1=proc.time(); iquery(DB, "build(<val:string>[i=1:3], '[(01),(02),(03)]', true)", return=T, binary=FALSE); proc.time()-t1
  i val
1 1   1
2 2   2
3 3   3
   user  system elapsed 
  0.048   0.027   0.074 
> t1=proc.time(); f=iquery(DB, "build(<val:string>[i=1:3], '[(01),(02),(03)]', true)", return=T, binary=FALSE); proc.time()-t1
   user  system elapsed 
  0.053   0.025   0.078 
> class(f$val)
[1] "integer"
```

**Comment by bwlewis** [comment]
Yeah, I guess this can use better documentation. When `binary=FALSE` is set, the package parses the returned text output with `read.table()`, and that function is doing the unwanted conversion for you. The help page for `iquery()` says:

```
    ...: additional options passed to ‘read.table’ when
          ‘binary=FALSE’
```

so that means that you can include arguments to `read.table()` here, including arguments that explicitly control the types. For instance, this does what you want:

```{r}
library(scidb)
db = scidbconnect()
iquery(db, "build(<val:string>[i=1:3], '[(01),(02),(03)]', true)", return=T, binary=FALSE, colClasses=c("integer", "character"))
#     i val
# 1 1  01
# 2 2  02
# 3 3  03
```

So I guess maybe more doc or an example is warranted to help here. I don't see a bug though.

**Comment by bwlewis** [comment]
Consider adding a default colClasses argument when the return types are known.
