### ISSUE TITLE
Strange scoping error when using "$"

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#173]
```R
> DB = scidbconnect(...)
> as.R(DB$list())               #works fine
> foo = function(db = DB) { as.R(db$list()) }        
> foo()                    #ERROR:
 Error in eval(expr, envir, enclos) : object 'db' not found 

7. | eval(expr, envir, enclos)
6. | eval(as.list(match.call())[[1]])
5. | db$list()
4. | inherits(x, "scidb")
3. | stopifnot(inherits(x, "scidb"))
2. | as.R(db$list())
1. | foo()
```

**Comment by apoliakov** [comment]
This works fine, for example:

```R
> bar = function(db = DB) { iquery(db, "list()", return=T) }
> bar()
```

**Comment by ksens** [comment]
This turns out to be super important when building functions or packages using `scidbr` or in fact any non-standard evaluation functions. I just spent a day removing NSE usage of `scidbr` from my package `scidb4gh`. 

@bwlewis you had explained why this happens, but I do not remember the technicalities exactly. In fact, you had pointed to a `dplyr` note on non-standard evaluation -- saying "do not use dplyr's NSE syntax to build functions... use the standard evaluation instead". Maybe you can point us to that again?

My current take away is this:

- when I am building functions / packages, I should not use the `db$OPERATOR` syntax inside the functions. 

PS: Adding another example of the same (mainly for my future reference):

```R
rm(list = ls())

my_show = function (arr, con = NULL) 
{
  if (is.null(con)) con = globalcon$db
  cat("Passed this\n")
  zz = con$db$show(arr)
  cat("Passed this too\n")
  zz
}

my_show_v2 = function (arr, con = NULL) 
{
  if (is.null(con)) con = globalcon$db
  cat("Passed this\n")
  zz = scidb(db, paste0("show(", arr@name, ")"))
  cat("Passed this too\n")
  zz
}

library(scidb)
db = scidbconnect(host = '127.0.0.1/shim/', port = NULL, username = 'root',
                  password = 'Paradigm4', protocol = 'https')


globalcon = new.env()
globalcon$db = db

x = as.scidb(globalcon$db, '1')

cat("# METHOD 1 \n")
try(my_show(arr = x, con = globalcon))
# METHOD 1 
# Passed this
# Error in eval(as.list(match.call())[[1]]) : object 'con' not found

cat("# METHOD 2 - pass arg \n")
try(my_show_v2(arr = x, con = globalcon))
# Works OK
cat("# METHOD 2 - do not pass arg \n")
try(my_show_v2(arr = x))
# Works OK
```

Only difference with @apoliakov 's example is that I am using an environment variable `globalcon` instead of a global `DB` object. As mentioned before, adding the example here mainly for my own reference.

**Comment by jrivers96** [comment]
The below fails for I believe the same reasons. This means that a user has to use strings to construct AFL queries when using the parallel library. 

> fparallel = function(pixel)
> {
>  library('scidb')
>  db <- scidbconnect(username="root",password="Paradigm4", protocol = c("https"), port=8083)
>  foo = as.R(db$list())
>  print(foo)
> }
> 
> library(parallel)
> cl = makePSOCKcluster(4, outfile='/tmp/foofoo')
> times = clusterApply(cl, s, fparallel)

**Comment by bwlewis** [comment]
This should be fixed now in the master.  The issue was really just sloppy scoping on my part, sorry.  I fixed that and also streamlined that handler code a little.

Kriti recently pointed out that lots of progress for this kind of non-standard evaluation stuff has been made in the tidyverse -- specifically in the rlang package. They use a peculiar thing in R called a formula in very nice ways.  We can probably move in that direction to use those ideas instead of the somewhat lame R(*) escaping syntax to include R expressions in AFL.

But for now this fix may solve many of your problems. Please let me know how it works...
