### ISSUE TITLE
Extreme numeric values get truncated on upload

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#193]
Example: a low value becomes 0 if uploaded as part of a data.frame. This does not apply to vector uploads:

```R
> x = data.frame(a = 1.23456e-50)
> y = as.scidb(db, x)
> as.R(y)
  i a
1 1 0
```

It looks like this line is the culprit:
https://github.com/Paradigm4/SciDBR/blob/5486b1e201856e7c157910db5faadbbe7ad032e5/R/internal.R#L655

Workaround:
```R
> x2 = x
> x2$a = as.character(x2$a)
> y2 = as.scidb(db, x2, types="double")
> as.R(y2)
  i           a
1 1 1.23456e-50
```

@bwlewis is this right? Did I miss something?

**Comment by bwlewis** [comment]
That's right. The default df2scidb method transfers data as text, optionally using aio_input. Becasue data frames can contain anything, and SciDB likes text input for many attributes we originally used that approach.

Interestingly, I tried at first to use this much more sensible format:   `sprintf("%e", ...)` in the conversion (which would have worked fine for your example), but we had to abandon that because at the time SciDB CSV input could not handle scientific notation. (keep in mind, this was written many years ago).

If that has changed, then that format should also be changed!

**Comment by apoliakov** [comment]
Hey @bwlewis thanks!
Yeah looks like it was changed. Is the fix as simple as replacing "%.16f" with "%e" ?

**Comment by bwlewis** [comment]
yes i think so, try that...

**Comment by rvernica** [comment]
I replaced `%.16f` with `%e`. Some of the tests fail with the default `all.equal` tolerance of `1.5e-8`. E.g.,
```R
> all.equal(df, x)
  [1] "Component “V1”: Mean relative difference: 6.199794e-08"  
  [2] "Component “V2”: Mean relative difference: 6.19292e-08"   
  [3] "Component “V3”: Mean relative difference: 3.823863e-08"  
...
```
If I increase the tolerance to `1e-7` they work fine.
