### ISSUE TITLE
Reviewer comments from CRAN

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#213]
Need to make some changes to resubmit the package to CRAN (following #209 , #210 ). 

Pasting the review comments below. Assigning to myself. 

- [x] Please do not start the description with "This package", package name, title or similar.
- [x] The Description field is intended to be a (one paragraph) description of what the package does and why it may be useful. Please add more details about the package functionality and implemented methods in your Description text.
- [x] Warning: Unexecutable code in man/iquery.Rd: 
return:
- [x] Warning: Unexecutable code in man/schema.Rd:
name start:
- [x] You write information messages to the console that cannot be easily suppressed.
It is more R like to generate objects that can be used to extract the
information a user is interested in, and then print() that object.
Instead of print()/cat() rather use message()/warning()  or
if(verbose)cat(..) (or maybe stop()) if you really have to write text to
the console.
(except for print, summary, interactive functions)
- [x] Please do not modify the global environment (e.g. by using <<-) in your
functions. This is not allowed by the CRAN policies.
- [x] Please always add all authors, contributors and copyright holders in the
Authors@R field with the appropriate roles.
- [x] From CRAN policies you agreed to:
"... Where copyrights are held by an entity other than the package
authors, this should preferably be indicated via ‘cph’ roles in the
‘Authors@R’ field, or using a ‘Copyright’ field (if necessary referring
to an inst/COPYRIGHTS file)."
e.g.: Paradigm4, Inc., SciDB, Inc.
- [ ] Please explain in the submission comments what you did about this issue.
- [ ]  Additionally:
Have the problems why your package was archived been fixed?
Please write this in the submission comments as well.

Please fix and resubmit.

**Comment by ksens** [comment]
@arko-bhattacharya 

While working on this ticket, please also review this PR https://github.com/Paradigm4/SciDBR/pull/208 and the doc linked at that ticket (https://github.com/Paradigm4/cs_tool_kit/blob/master/tips_for_R/uploading_packages_to_cran.md) to get some background on recent CRAN related work for this repo.

**Comment by arko-bhattacharya** [comment]
Response to reviewer comments - 

- [ ] Please do not start the description with "This package", package name, title or similar.
- [ ] The Description field is intended to be a (one paragraph) description of what the package does and why it may be useful. Please add more details about the package functionality and implemented methods in your Description text.

> We have updated the 'Description' field with a brief on SciDB, its properties and how the package 'scidb' allows users to interact with an active SciDB session.

- [ ] Warning: Unexecutable code in man/iquery.Rd: 
- [ ] Warning: Unexecutable code in man/schema.Rd:

> The code which exists in the ./man folder is unexecutable as conecting to an active SciDB session is a pre-requisite.

- [ ] You write information messages to the console that cannot be easily suppressed.
It is more R like to generate objects that can be used to extract the information a user is interested in, and then print() that object. Instead of print()/cat() rather use message()/warning()  or if(verbose)cat(..) (or maybe stop()) if you really have to write text to the console. (except for print, summary, interactive functions)

> We have updated all functions with print OR cat statements with relevant message or warning statements. 
> The functions where modeified are -


- [ ] Please do not modify the global environment (e.g. by using <<-) in your functions. This is not allowed by the CRAN policies.

> We have removed global environment modification. The function which was causing this has been removed from the package.

- [ ] Please always add all authors, contributors and copyright holders in the Authors@R field with the appropriate roles.
- [ ] From CRAN policies you agreed to:
"... Where copyrights are held by an entity other than the package authors, this should preferably be indicated via ‘cph’ roles in the ‘Authors@R’ field, or using a ‘Copyright’ field (if necessary referring to an inst/COPYRIGHTS file)." e.g.: Paradigm4, Inc., SciDB, Inc.

> We have updated the authors field with Paradigm4 Inc. and assigned it a 'cph' role.

- [ ] Please explain in the submission comments what you did about this issue.
>

- [ ]  Additionally: Have the problems why your package was archived been fixed?
>

- [ ] Please write this in the submission comments as well.

>
