### ISSUE TITLE
iquery fails to return query results if revealgenomics is loaded alongside scidb

### ISSUE THREAD

**Issue by cgaray-p4** [Paradigm4/SciDBR#294]
I see this behavior on a new installation of SciDB 23.2 with scidb 4.0 and revealgenomics 0.9.6.7:

```
> library(scidb)
> db = scidb::scidbconnect(
  host='localhost',
  username = 'scidbadmin',
  password = readLines("~/.scidb_pass"),
  port = 8083,
  protocol = 'https'
)
> scidb::iquery(db, "op_scidbversion()", return=T)
  i major minor patch
1 0    22     6     1
> library(revealgenomics)
> scidb::iquery(db, "op_scidbversion()", return=T)
Error: HTTP error 406
UserException in file: src/array/TemplateParser.cpp function: parse line: 104 instance: s0-i0 (0)
Error id: scidb::SCIDB_SE_EXECUTION::SCIDB_LE_ATTRIBUTES_MISMATCH
Error description: Error during query execution. Attributes mismatch.
Failed query id: 0.1684930597246196554
```

**Comment by ksens** [comment]
@mpietras-p4 @cgaray-p4 

Can you do a few more checks here:
- Does this repro-s on a pre scidb 23 system? 
- Does this happen if you load biobank package along with scidbR? 

This seems to be a pretty important issue because this potentially prevents revealgenomics and biobank to co-exist on a system. @cgaray-p4 has a workaround by using new Client API instead of shim, but I would ideally like us to dig into this a bit more.

**Comment by mpietras-p4** [comment]
I wasn't able to repro the issue on the multiomics server. 

One thing to check - does this occur on Scidb 23 if `options("scidb.aio"=TRUE)` gets run _without_ loading revealgenomics or biobank?  If there's something wrong with the aio path, you'd see iquery working with just `scidbr` loaded but not once `revealgenomics` or `biobank` are loaded, since all our packages make that setting change at load time.
