### ISSUE TITLE
Different download speeds: R terminal versus RStudio Server

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#72]
I verified it's the same / single version of R, 3.2.2. Same array.

In the R terminal the download is a lot faster:

``` R
> t1= proc.time(); f=f[]; proc.time()-t1;
   user  system elapsed 
288.586  22.373 366.192 
```

In Rstudio server it's a lot slower:

``` R
> t1=proc.time();
>   r = res[]
>   proc.time()-t1;
    user   system  elapsed 
 293.338   14.953 4960.735 
```

I also noticed when we're doing it through RStudio, the CPU is at near 1%. When using the R terminal, the CPU of the R process is at 100%. Not sure if it's a shim issue or what?

**Comment by apoliakov** [comment]
The array in question is 3D, 1 double null attribute, 1.5B values.

**Comment by bwlewis** [comment]
This is due to the insertion of a curl callback to handle user interrupt. See line https://github.com/Paradigm4/SciDBR/blob/master/R/utility.R#L1053

It's in a way both a problem of RCurl, which has lousy interrupt capability (using a callback), and RStudio, which prohibits custom slow-level interrupt definitions.

I think that the best solution is to replace RCurl if possbible with the new curl package, https://cran.r-project.org/web/packages/curl/index.html

Until then, you can get fast speeds in RStudio by setting the option:

options(scidb.interrupt=FALSE)

Beware that this inhibits user interrupt however.

**Comment by bwlewis** [comment]
Might be fixed in commit e0241410e530be1832229f39db0bd034daa89ef2  still need to test this

**Comment by apoliakov** [comment]
Just tried a case I was working on - looks like still an issue. Seeing 1.3s vs 1s

**Comment by bwlewis** [comment]
Are you sure that they are different? I am seeing a large variance in download times.

Although, the large variance in itself is a bit disconcerting.

**Comment by bwlewis** [comment]
The high variance mentioned above is more like occasional outlier, but still puzzling.
